### ISSUE TITLE
Pawns without inspectors causing errors

### ISSUE THREAD

**Issue by t00137667** [AndroidQuazar/VanillaPsycastsExpanded#2]
When using another mod that has lightweight pawns , the inspector window doesn't appear. And an error is constantly generated while the pawn is selected.

[ErrorStackTrace.txt](https://github.com/AndroidQuazar/VanillaPsycastsExpanded/files/9234407/ErrorStackTrace.txt)

https://github.com/AndroidQuazar/VanillaPsycastsExpanded/blob/d5bb66c4c6fbe29187a407773897f195bf684e30/1.3/Source/VanillaPsycastsExpanded/UI/ITab_Pawn_Psycasts.cs#L41

The ITab_Pawn_Psycasts() assumes all humanlike pawns have inspectors. 
Would it be possible to add a def.inspectorTabs != null condition to the method?

**Comment by legodude17** [comment]
Fixed in [3b6ba5](https://github.com/AndroidQuazar/VanillaPsycastsExpanded/commit/3b6ba5d17704801af97ffb208460ea3d091ece51).
