### ISSUE TITLE
`AnimalThingBase.VPE_ConstructBase.VPE_RockConstruct` and `...VPE_SteelConstruct` not properly destroyed upon `settlement_abandon`

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [AndroidQuazar/VanillaPsycastsExpanded#3]
The issue:
if you abandon a settlement with  `AnimalThingBase.VPE_ConstructBase.VPE_RockConstruct` or `AnimalThingBase.VPE_ConstructBase.VPE_SteelConstruct` the reserved `psychicEntropy` (most commonly referred to as `heat`) (20 per construct) is not unreserved 

How to replicate:
1) create a new world drop in it and learn the `psycast.abilities`:
`VFECore.Abilities.AbilityDef.VPE_PsycastBase.VPE_RockConstruct`
`VFECore.Abilities.AbilityDef.VPE_PsycastBase.VPE_SteelConstruct`
2) create a few constucts using those `psycast.abilities`
`AnimalThingBase.VPE_ConstructBase.VPE_SteelConstruct` `AnimalThingBase.VPE_ConstructBase.VPE_RockConstruct`
3) create a caravan and do not bring those "constructs" with you
4) execute `settlement_abandon()` command on that settlement (the easiest way to do is by using the GUI)
5) settle in a different tile and pay check the `psychicEntropy` you still see it is still reserved (even though during settlement_abandon()` the "constructs" would have been destroyed)

Note: i assume the same behaviour might be excibited by:   `VFECore.Abilities.AbilityDef.VPE_PsycastBase.VPE_Skipdoor` i did not test 

What i am assuming is happening is that the constructs are not actually destroied but instead "lost" in similar way that if you lose a pawn or animal during a `settlement_abandon` it is possible to see them in the future (in a quest or in another faction for example) the same thing is happening to the constructs because they are `AnimalThingBase` even though such a behaviour should not apply to constructs since they have `AnimalBehaviours.AnimalsDisabledFromQuestsDef`

Update same behaviour is observed in a 'caravan lost' 'event'

--------------------------------
1) How can i unreserve `psychicEntropy` from my pawn in my game save
**update: Using `Character Editor` mod i not was able to unreserve the entropy 
**update: i was able to fix the issue on my save my editing VanillaPsycastsExpanded.Hediff_PsycastAbilities.minHeat value of my pawn
2) do you need more info to replicate/understand the issue

Thanks

**Comment by legodude17** [comment]
Fixed in [bc095a](https://github.com/AndroidQuazar/VanillaPsycastsExpanded/commit/bc095a7a4e3dcd78860303619733e90b29cb2d34).
